{{ dbt_date.get_date_dimension('2000-01-01', '2030-12-31') }}

-- This file is auto-generated by dbt-date package.
-- SELECT
--     TO_CHAR(date_day, 'YYYYMMDD')::DATE AS date_sk,
--     date_day AS full_date,
--     day_of_month,
--     month_of_year AS month_of_year,
--     month_name,
--     quarter_of_year AS quarter_of_year,
--     year_number AS year_no
-- FROM {{ dbt_date.get_date_dimension('2000-01-01', '2030-12-31') }}