{{ dbt_date.get_date_dimension('2000-01-01', '2030-12-31') }}

-- This file is auto-generated by dbt-date package.
SELECT
    TO_CHAR(date_day, 'YYYYMMDD')::INTEGER AS date_sk,
    date_day AS date,
    day_of_month,
    month_of_year AS month,
    month_name,
    quarter_of_year AS quarter,
    year_number AS year
FROM {{ dbt_date.get_date_dimension('2000-01-01', '2030-12-31') }}