version: 2

sources:
  - name: public_data
    database: amazon_reviews_dwh
    schema: public

    tables:
      - name: stg_reviews_data
        description: "Raw review data processed by Airflow ingestion script."
        loaded_at_field: ingestion_timestamp
        columns:
          - name: reviewer_id
          - name: product_id
          - name: reviewer_name
          - name: rating
          - name: review_summary
          - name: sentiment
          - name: unix_review_timestamp
          - name: review_timestamp
          - name: ingestion_timestamp

      - name: stg_metadata_category
        description: "Raw metadata processed by Airflow ingestion script."
        loaded_at_field: ingestion_timestamp
        columns:
          - name: product_id
          - name: image_url
          - name: sales_category
          - name: sales_rank
          - name: first_category
          - name: product_title
          - name: product_description
          - name: product_price
          - name: related_products
          - name: product_brand
          - name: ingestion_timestamp

models:
  - name: dim_reviewer
    description: "Dimension table for reviewers"
    columns:
      - name: reviewer_id
        data_tests:
          - unique
          - not_null
      - name: reviewer_name
        data_tests:
          - not_null
      - name: review_summary
      - name: sentiment
        data_tests:
          - accepted_values:
              values: ['Positive', 'Negative', 'Neutral', NULL]
      - name: review_date
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: date

  - name: dim_product
    description: "Dimension table for products"
    columns:
      - name: product_id
        data_tests:
          - unique
          - not_null
      - name: product_title
        data_tests:
          - not_null
      - name: brand
        data_tests:
          - not_null
      - name: category
        data_tests:
          - not_null
      - name: price
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_in_type_list:
              column_type_list: ['numeric', 'float', 'double precision']
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 99999999.99

  - name: dim_date
    description: "Dimension table for dates"
    columns:
      - name: date_sk
        data_tests:
          - unique
          - not_null
          - dbt_expectations.expect_column_values_to_match_regex:
              regex: '^\d{8}$' # YYYYMMDD format
      - name: date
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: date
      - name: day_of_month
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 1
              max_value: 31
      - name: month
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 1
              max_value: 12
      - name: month_name
        data_tests:
          - not_null
      - name: quarter
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 1
              max_value: 4
      - name: year
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 2000
              max_value: 2030

  - name: fact_review
    description: "Fact table with review and its metadata (SCD2 dimensions)"
    meta:
      dbt_incremental_strategy: merge
      unique_key: review_sk

    columns:
      - name: review_sk
        data_tests:
          - unique
          - not_null
      - name: reviewer_id
        data_tests:
          - not_null
          - relationships:
              to: ref('dim_reviewer_scd2')
              field: dbt_scd_id
      - name: product_id
        data_tests:
          - not_null
          - relationships:
              to: ref('dim_product_scd2')
              field: dbt_scd_id
      - name: date_sk
        data_tests:
          - not_null
          - relationships:
              to: ref('dim_date')
              field: date_sk
      - name: rating
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 1.0
              max_value: 5.0
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: float
      - name: sentiment
        data_tests:
          - accepted_values:
              values: ['Positive', 'Negative', 'Neutral', 'None']
          - not_null
      - name: ingestion_timestamp
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp