version: 2

sources:
  - name: public_data
    database: amazon_reviews_dwh
    schema: public

    tables:
      - name: processed_reviews_data
        description: "Raw reviews dataset."
        loaded_at_field: ingestion_timestamp
        columns:
          - name: reviewer_id
          - name: product_id
          - name: reviewer_name
          - name: rating
          - name: review_summary
          - name: sentiment
          - name: unix_review_timestamp
          - name: review_timestamp
          - name: ingestion_timestamp

      - name: processed_metadata_category
        description: "Raw metadata dataset."
        loaded_at_field: ingestion_timestamp
        columns:
          - name: product_id
          - name: image_url
          - name: sales_category
          - name: sales_rank
          - name: first_category
          - name: product_title
          - name: product_description
          - name: product_price
          - name: related_products
          - name: product_brand
          - name: ingestion_timestamp

models:
  # Staging Models (from dbt/models/staging/)
  - name: stg_reviews_data
    description: "Staging model for raw review data"
    columns:
      - name: reviewer_id
        tests:
          - not_null
      - name: product_id
        tests:
          - not_null
          - productid_format
      - name: reviewer_name
      - name: rating
      - name: review_summary
      - name: sentiment
      - name: unix_review_timestamp
      - name: review_timestamp
      - name: ingestion_timestamp

  - name: stg_metadata_category
    description: "Staging model for raw products metadata"
    columns:
      - name: product_id
        tests:
          - not_null
          - productid_format
      - name: image_url
      - name: sales_category
      - name: sales_rank
      - name: first_category
      - name: product_title
      - name: product_description
      - name: product_price
      - name: related_products
      - name: product_brand
      - name: ingestion_timestamp

  # Marts Models (from dbt/models/marts/)
  - name: dim_date
    description: "Dimension table for dates, generated by dbt_date"
    columns:
      - name: date_day
        tests:
          - unique
          - not_null
      - name: day_of_month
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 1
              max_value: 31
      - name: month_of_year
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 1
              max_value: 12
      - name: month_name
        tests:
          - not_null
      - name: quarter_of_year
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 1
              max_value: 4
      - name: year_number
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 2000
              max_value: 2030

  - name: fact_review
    description: "Fact table"
    columns:
      - name: review_sk
        tests:
          - unique
          - not_null
      - name: reviewer_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_reviewer_scd2')
              field: reviewer_id
      - name: product_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_product_scd2')
              field: product_id
      - name: date_sk
        tests:
          - not_null
          - relationships:
              to: ref('dim_date')
              field: date_day
      - name: rating
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 1.0
              max_value: 5.0
      - name: sentiment
        tests:
          - accepted_values:
              values: ['Positive', 'Negative', 'Neutral', 'None']
          - not_null
      - name: review_summary
      - name: ingestion_timestamp
        tests:
          - not_null