version: 2

sources:
  - name: public_data
    database: amazon_reviews_dwh
    schema: public

    tables:
      - name: processed_reviews_data
        description: "Raw review data ingested by Airflow scripts from the reviews dataset."
        loaded_at_field: ingestion_timestamp
        columns:
          - name: reviewer_id
          - name: product_id
          - name: reviewer_name
          - name: rating
          - name: review_summary
          - name: sentiment
          - name: unix_review_timestamp
          - name: review_timestamp
          - name: ingestion_timestamp

      - name: processed_metadata_category
        description: "Raw metadata ingested by Airflow scripts from the metadata dataset."
        loaded_at_field: ingestion_timestamp
        columns:
          - name: product_id
          - name: image_url
          - name: sales_category
          - name: sales_rank
          - name: first_category
          - name: product_title
          - name: product_description
          - name: product_price
          - name: related_products
          - name: product_brand
          - name: ingestion_timestamp

models:
  # Staging Models (from dbt/models/staging/)
  - name: stg_reviews_data
    description: "Staging model for raw review data, cleaning and standardizing the base."
    columns:
      - name: reviewer_id
        data_tests:
          - not_null
      - name: product_id
        data_tests:
          - not_null
      - name: reviewer_name
      - name: rating
      - name: review_summary
      - name: sentiment
      - name: unix_review_timestamp
      - name: review_timestamp
      - name: ingestion_timestamp

  - name: stg_metadata_category
    description: "Staging model for raw product metadata, cleaning and standardizing the base."
    columns:
      - name: product_id
        data_tests:
          - not_null
      - name: image_url
      - name: sales_category
      - name: sales_rank
      - name: first_category
      - name: product_title
      - name: product_description
      - name: product_price
      - name: related_products
      - name: product_brand
      - name: ingestion_timestamp

  # Marts Models (from dbt/models/marts/)
  - name: dim_date
    description: "Dimension table for dates, generated by dbt_date."
    columns:
      - name: date_sk
        data_tests:
          - unique
          - not_null
          - dbt_expectations.expect_column_values_to_match_regex:
              regex: '^\d{8}$' # YYYYMMDD format
      - name: date
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: date
      - name: day_of_month
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 1
              max_value: 31
      - name: month
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 1
              max_value: 12
      - name: month_name
        data_tests:
          - not_null
      - name: quarter
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 1
              max_value: 4
      - name: year
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 2000
              max_value: 2030

  - name: fact_review
    description: "Fact table recording individual review events, linked to SCD2 dimensions."
    columns:
      - name: review_sk
        data_tests:
          - unique
          - not_null
      - name: reviewer_id
        data_tests:
          - not_null
          - relationships:
              to: ref('dim_reviewer_scd2')
              field: reviewer_id
      - name: product_id
        data_tests:
          - not_null
          - relationships:
              to: ref('dim_product_scd2')
              field: product_id
      - name: date_sk
        data_tests:
          - not_null
          - relationships:
              to: ref('dim_date')
              field: date_sk
      - name: rating
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 1.0
              max_value: 5.0
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: float
      - name: sentiment
        data_tests:
          - accepted_values:
              values: ['Positive', 'Negative', 'Neutral', 'None']
          - not_null
      - name: review_summary
      - name: ingestion_timestamp
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp